#!/usr/bin/env bash
# {{AGENT_NAME}} — Invocation Script
#
# Wizard-generated. Loads the agent's prompt file and required context from disk,
# invokes the Claude CLI, writes outputs to defined disk locations using the atomic
# write pattern, captures exit status, and logs completion or failure.
#
# Usage: ./{{AGENT_NAME}}.sh [TASK_ID]
#
# If TASK_ID is omitted, a timestamp-based ID is generated.
#
# Generated from: /wizard/scripts/agent_invocation_template.sh
# Generated by wizard at setup for agent: {{AGENT_NAME}}
#
# SESSION LOCK: This script invokes a specialist agent as a CHILD of the Orchestrator's
# session. The Orchestrator (the control plane) owns the project-root maintenance_mode.md
# session lock — it claims the lock at startup and clears it at session end, and spawns
# specialists beneath that lock. A child specialist therefore does NOT re-check the lock
# (re-checking would block the Orchestrator's own spawns — the system would never run any
# specialist work). The session lock is enforced where a session STARTS (the Orchestrator's
# startup check). A scheduled job that invokes a specialist DIRECTLY, bypassing the
# Orchestrator, is an advanced exception and must declare its own lock behavior at that
# entry point — it does not inherit this script's child semantics.

set -euo pipefail

# ── Status-line convention (F-36 fix) ───────────────────────────────────────
# Every operator-runnable emitted script carries this SAME block (kept
# byte-identical on purpose -- see test_status_line_convention.py). It
# guarantees ONE unambiguous terminal line plus a real exit code no matter
# where or why the script exits: an explicit `exit N` below, or an exit
# `set -e` forces on a line this script's own logic never anticipated. A
# `!`-run command must never finish silently (empty output, exit 0) and be
# mistaken for having done nothing (dogfood finding F-36).
_STATUS_LINE_REPORTED=false
_report_status_line() {
  local _exit_code=$?
  trap - EXIT
  if [ "$_STATUS_LINE_REPORTED" != true ]; then
    _STATUS_LINE_REPORTED=true
    if [ "$_exit_code" -eq 0 ]; then
      echo "RESULT: done"
    else
      echo "RESULT: failed (exit ${_exit_code})" >&2
    fi
  fi
  exit "$_exit_code"
}
trap _report_status_line EXIT
# ── end status-line convention ──────────────────────────────────────────────

# --- Configuration ---
AGENT_NAME="{{AGENT_NAME}}"
AGENT_MODEL="{{AGENT_MODEL}}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
TASK_ID="${1:-$(date +%Y%m%d_%H%M%S)}"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Python interpreter pin (F-35 fix). If this project has a Python component, its pinned
# project-local venv already exists (created by start-session.sh's venv-bootstrap on
# first boot). Prefer it over a bare `python3` here too -- this matters specifically for
# a cron-triggered run, which invokes THIS script directly and bypasses start-session.sh
# entirely. A system with no Python component has no .venv/ and this is a silent no-op.
if [[ -x "$PROJECT_ROOT/.venv/bin/python" ]]; then
  export PATH="$PROJECT_ROOT/.venv/bin:$PATH"
fi

# --- Required file paths ---
PROMPT_FILE="$PROJECT_ROOT/agents/prompts/${AGENT_NAME}_prompt.md"
SESSION_BOOTSTRAP="$PROJECT_ROOT/session_bootstrap.md"
PROJECT_INSTRUCTIONS="$PROJECT_ROOT/project_instructions.md"
VISION_FILE="$PROJECT_ROOT/vision.md"

# --- Log file paths ---
SESSION_LOG="$PROJECT_ROOT/logs/session_log.md"
ERROR_LOG="$PROJECT_ROOT/logs/error_log.md"

# --- Output configuration ---
# These values are specific to this agent and set by the wizard at generation time.
OUTPUT_DIR="$PROJECT_ROOT/{{OUTPUT_DIRECTORY}}"
HANDOFF_DIR="$PROJECT_ROOT/agents/handoffs"
CHECKPOINT_FILE="$PROJECT_ROOT/agents/checkpoints/${AGENT_NAME}_${TASK_ID}_checkpoint.md"
# The agent self-reports HOW its session ended into this sentinel; this script reads it to
# compose the one authoritative handoff envelope (single writer). Hidden + .stop_reason suffix
# so it is never mistaken for a *_handoff.json the Orchestrator consumes.
STOP_SENTINEL="$HANDOFF_DIR/.${AGENT_NAME}_${TASK_ID}.stop_reason"

# The six allowed stop reasons (the emitted-system handoff contract). A sentinel value outside
# this set is treated as "no valid report" and the script defaults to completed (+ a flag).
valid_stop_reason() {
  case "$1" in
    completed|budget_exceeded|error|timeout|user_cancelled|deferred) return 0 ;;
    *) return 1 ;;
  esac
}

# --- Additional context files specific to this agent ---
# Add paths to files this agent needs beyond the three foundational documents.
# Leave empty if no additional context is required.
ADDITIONAL_CONTEXT_FILES=(
  {{ADDITIONAL_CONTEXT_FILES}}
)

# ============================================================
# Pre-flight checks
# ============================================================

# 1. Prompt file check — abort if the agent's prompt file is missing
if [[ ! -f "$PROMPT_FILE" ]]; then
  echo "[${TIMESTAMP}] ${AGENT_NAME} [ERROR]: Prompt file not found: $PROMPT_FILE" >&2
  echo "| ${TIMESTAMP} | ${AGENT_NAME} | FAILED | Prompt file missing: $PROMPT_FILE | task:${TASK_ID} |" >> "$ERROR_LOG" || true
  exit 1
fi

# 2. Required foundational context check — abort if any are missing
REQUIRED_CONTEXT=("$SESSION_BOOTSTRAP" "$PROJECT_INSTRUCTIONS" "$VISION_FILE")
for context_file in "${REQUIRED_CONTEXT[@]}"; do
  if [[ ! -f "$context_file" ]]; then
    echo "[${TIMESTAMP}] ${AGENT_NAME} [ERROR]: Required context file missing: $context_file" >&2
    echo "| ${TIMESTAMP} | ${AGENT_NAME} | FAILED | Required context file missing: $context_file | task:${TASK_ID} |" >> "$ERROR_LOG" || true
    exit 1
  fi
done

# 4. Ensure output and handoff directories exist
mkdir -p "$OUTPUT_DIR"
mkdir -p "$HANDOFF_DIR"
mkdir -p "$PROJECT_ROOT/agents/checkpoints"

# Clear any stale stop-reason sentinel so only THIS run's report is read.
rm -f "$STOP_SENTINEL"

# ============================================================
# Build the from-disk context file list
# The agent reads these files itself in the session before acting (foundational
# document integrity — read this session, never recalled). They are NAMED in the
# task prompt below; there is no CLI flag that loads files into the session, so the
# agent reads them from disk relative to the project root (we cd there before the run).
# ============================================================

CONTEXT_FILES=("$SESSION_BOOTSTRAP" "$PROJECT_INSTRUCTIONS" "$VISION_FILE")
for f in "${ADDITIONAL_CONTEXT_FILES[@]+"${ADDITIONAL_CONTEXT_FILES[@]}"}"; do
  [[ -n "$f" ]] && CONTEXT_FILES+=("$f")
done

# ============================================================
# Invoke Claude CLI — atomic write pattern
# Write output to a temp file first, then rename to final path.
# This prevents partially-written files from being consumed by
# downstream agents if the run is interrupted.
# ============================================================

# Run from the project root so the agent's relative reads/writes (and the from-disk
# foundational-document reads named in the task prompt) resolve correctly.
cd "$PROJECT_ROOT"

TEMP_OUTPUT=$(mktemp "${OUTPUT_DIR}/.${AGENT_NAME}_${TASK_ID}.tmp.XXXXXX")
FINAL_OUTPUT="${OUTPUT_DIR}/${AGENT_NAME}_${TASK_ID}_output.md"

echo "[${TIMESTAMP}] ${AGENT_NAME} [START]: task ${TASK_ID}"
echo "| ${TIMESTAMP} | ${AGENT_NAME} | STARTED | task:${TASK_ID} |" >> "$SESSION_LOG"

# --append-system-prompt loads the agent's prompt file as its system prompt; the agent
# reads its foundational documents from disk (named below). --permission-mode acceptEdits
# lets the headless agent write its outputs/checkpoints without an interactive prompt
# (there is no TTY in -p mode); the agent's own prompt still enforces the Tier-1 ask-first
# gates. The agent's foundational-document-integrity constraint lives in its prompt file.
# --fallback-model degrades to the standard-context model if this agent's tier resolves to
# the 1M-context [1m] variant and that variant is unavailable on this account/plan. For a
# non-1M tier the fallback equals the model (no degradation). ${AGENT_MODEL%\[1m\]} strips a
# trailing literal "[1m]" suffix.
FALLBACK_MODEL="${AGENT_MODEL%\[1m\]}"
EXIT_CODE=0
claude \
  --model "$AGENT_MODEL" \
  --fallback-model "$FALLBACK_MODEL" \
  --permission-mode acceptEdits \
  --append-system-prompt "$(cat "$PROMPT_FILE")" \
  --print \
  "You are ${AGENT_NAME}. Your role, permission boundary, and completion criteria are in your system prompt (your prompt file, appended above). You are running with the project root as your working directory.

Task ID: ${TASK_ID}
Checkpoint file: ${CHECKPOINT_FILE}
Stop-reason sentinel: ${STOP_SENTINEL}

Before doing anything:
1. Read your foundational documents from disk this session — do not operate from memory: ${CONTEXT_FILES[*]}
2. Declare your blast radius — list every file and directory you intend to write to.
3. Verify all declared write targets are within your permitted directories.
4. Write a step-by-step plan to ${CHECKPOINT_FILE} before beginning.

Then execute your task. Write all outputs to disk. Update the checkpoint file as each step completes.

When your session ends — success or failure — write your stop reason, and nothing else, to the stop-reason sentinel file named above. Its entire contents must be exactly one of: completed, budget_exceeded, error, timeout, user_cancelled, deferred. The invocation script reads it to record how your session ended; you do not write the handoff envelope yourself." \
  > "$TEMP_OUTPUT" 2>&1 || EXIT_CODE=$?

# ============================================================
# Handle exit status — rename temp file to final or .failed
# ============================================================

# This script is the SINGLE writer of the handoff envelope (the Orchestrator's record of how
# the run ended). It composes the envelope from the process exit status + the agent's
# self-reported stop reason, and publishes it atomically (temp -> rename) so the Orchestrator
# never reads a half-written file. The agent never writes the envelope itself.
FINAL_HANDOFF="${HANDOFF_DIR}/${AGENT_NAME}_${TASK_ID}_handoff.json"

if [[ $EXIT_CODE -eq 0 ]]; then
  # Atomic rename: temp → final
  mv "$TEMP_OUTPUT" "$FINAL_OUTPUT"

  echo "[${TIMESTAMP}] ${AGENT_NAME} [COMPLETE]: task ${TASK_ID} → $FINAL_OUTPUT"
  echo "| ${TIMESTAMP} | ${AGENT_NAME} | COMPLETED | task:${TASK_ID} | output:${FINAL_OUTPUT} |" >> "$SESSION_LOG"

  # Clean exit: honor the agent's self-reported stop reason if it wrote a valid one (so a
  # "deferred"/"budget_exceeded" session is NOT silently recorded as "completed"); otherwise
  # default to completed and flag that the agent did not report. A clean exit never overrides
  # a valid agent report.
  STOP_REASON="completed"
  FLAGS=""
  if [[ -f "$STOP_SENTINEL" ]]; then
    REPORTED="$(tr -d '[:space:]' < "$STOP_SENTINEL")"
    if valid_stop_reason "$REPORTED"; then
      STOP_REASON="$REPORTED"
    else
      FLAGS='"script_default_stop_reason_invalid_report"'
    fi
  else
    FLAGS='"script_default_stop_reason_no_report"'
  fi

  HANDOFF_TMP=$(mktemp "${HANDOFF_DIR}/.${AGENT_NAME}_${TASK_ID}.handoff.XXXXXX")
  cat > "$HANDOFF_TMP" << HANDOFF_EOF
{
  "task_id": "${TASK_ID}",
  "agent": "${AGENT_NAME}",
  "status": "COMPLETE",
  "stop_reason": "${STOP_REASON}",
  "output_location": "${FINAL_OUTPUT}",
  "inputs_consumed": ["${PROMPT_FILE}", "${SESSION_BOOTSTRAP}", "${PROJECT_INSTRUCTIONS}", "${VISION_FILE}"],
  "outputs_produced": ["${FINAL_OUTPUT}"],
  "flags": [${FLAGS}],
  "audit_trail_ref": "${TIMESTAMP}"
}
HANDOFF_EOF
  mv "$HANDOFF_TMP" "$FINAL_HANDOFF"
  rm -f "$STOP_SENTINEL"

else
  # Preserve the failed output for diagnosis — rename with .failed extension
  FAILED_OUTPUT="${OUTPUT_DIR}/${AGENT_NAME}_${TASK_ID}_output.failed"
  mv "$TEMP_OUTPUT" "$FAILED_OUTPUT"

  echo "[${TIMESTAMP}] ${AGENT_NAME} [FAILED]: task ${TASK_ID} (exit code ${EXIT_CODE}) → $FAILED_OUTPUT" >&2
  echo "| ${TIMESTAMP} | ${AGENT_NAME} | FAILED | task:${TASK_ID} | exit:${EXIT_CODE} | output:${FAILED_OUTPUT} |" >> "$ERROR_LOG"

  # Process failure is authoritative: a nonzero exit publishes FAILED/error regardless of any
  # stop reason the agent reported — the sentinel cannot mask a crash.
  HANDOFF_TMP=$(mktemp "${HANDOFF_DIR}/.${AGENT_NAME}_${TASK_ID}.handoff.XXXXXX")
  cat > "$HANDOFF_TMP" << HANDOFF_EOF
{
  "task_id": "${TASK_ID}",
  "agent": "${AGENT_NAME}",
  "status": "FAILED",
  "stop_reason": "error",
  "output_location": "${FAILED_OUTPUT}",
  "inputs_consumed": ["${PROMPT_FILE}", "${SESSION_BOOTSTRAP}", "${PROJECT_INSTRUCTIONS}", "${VISION_FILE}"],
  "outputs_produced": [],
  "flags": ["exit_code_${EXIT_CODE}"],
  "audit_trail_ref": "${TIMESTAMP}"
}
HANDOFF_EOF
  mv "$HANDOFF_TMP" "$FINAL_HANDOFF"
  rm -f "$STOP_SENTINEL"

  exit $EXIT_CODE
fi
