#!/usr/bin/env bash
# {{AGENT_NAME}} — Invocation Script
#
# Wizard-generated. Loads the agent's prompt file and required context from disk,
# invokes the Claude CLI, writes outputs to defined disk locations using the atomic
# write pattern, captures exit status, and logs completion or failure.
#
# Usage: ./{{AGENT_NAME}}.sh [TASK_ID]
#
# If TASK_ID is omitted, a timestamp-based ID is generated.
#
# Generated from: /wizard/scripts/agent_invocation_template.sh
# Generated by wizard at setup for agent: {{AGENT_NAME}}
#
# IMPORTANT: Do not run this script while maintenance_mode.md exists in the project
# root. The orchestrator manages maintenance mode. Running an agent directly during
# an interactive session without checking maintenance mode can cause race conditions.

set -euo pipefail

# --- Configuration ---
AGENT_NAME="{{AGENT_NAME}}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
TASK_ID="${1:-$(date +%Y%m%d_%H%M%S)}"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# --- Required file paths ---
PROMPT_FILE="$PROJECT_ROOT/agents/prompts/${AGENT_NAME}_prompt.md"
SESSION_BOOTSTRAP="$PROJECT_ROOT/session_bootstrap.md"
PROJECT_INSTRUCTIONS="$PROJECT_ROOT/project_instructions.md"
VISION_FILE="$PROJECT_ROOT/vision.md"
MAINTENANCE_FLAG="$PROJECT_ROOT/maintenance_mode.md"

# --- Log file paths ---
SESSION_LOG="$PROJECT_ROOT/logs/session_log.md"
ERROR_LOG="$PROJECT_ROOT/logs/error_log.md"

# --- Output configuration ---
# These values are specific to this agent and set by the wizard at generation time.
OUTPUT_DIR="$PROJECT_ROOT/{{OUTPUT_DIRECTORY}}"
HANDOFF_DIR="$PROJECT_ROOT/agents/handoffs"
CHECKPOINT_FILE="$PROJECT_ROOT/agents/checkpoints/${AGENT_NAME}_${TASK_ID}_checkpoint.md"

# --- Additional context files specific to this agent ---
# Add paths to files this agent needs beyond the three foundational documents.
# Leave empty if no additional context is required.
ADDITIONAL_CONTEXT_FILES=(
  {{ADDITIONAL_CONTEXT_FILES}}
)

# ============================================================
# Pre-flight checks
# ============================================================

# 1. Maintenance mode check — skip if an interactive session is active
if [[ -f "$MAINTENANCE_FLAG" ]]; then
  echo "[${TIMESTAMP}] ${AGENT_NAME} [SKIP]: maintenance_mode.md is present. Cron run skipped." >&2
  echo "| ${TIMESTAMP} | ${AGENT_NAME} | SKIPPED | maintenance_mode.md present — cron run skipped | task:${TASK_ID} |" >> "$SESSION_LOG" || true
  exit 0
fi

# 2. Prompt file check — abort if the agent's prompt file is missing
if [[ ! -f "$PROMPT_FILE" ]]; then
  echo "[${TIMESTAMP}] ${AGENT_NAME} [ERROR]: Prompt file not found: $PROMPT_FILE" >&2
  echo "| ${TIMESTAMP} | ${AGENT_NAME} | FAILED | Prompt file missing: $PROMPT_FILE | task:${TASK_ID} |" >> "$ERROR_LOG" || true
  exit 1
fi

# 3. Required foundational context check — abort if any are missing
REQUIRED_CONTEXT=("$SESSION_BOOTSTRAP" "$PROJECT_INSTRUCTIONS" "$VISION_FILE")
for context_file in "${REQUIRED_CONTEXT[@]}"; do
  if [[ ! -f "$context_file" ]]; then
    echo "[${TIMESTAMP}] ${AGENT_NAME} [ERROR]: Required context file missing: $context_file" >&2
    echo "| ${TIMESTAMP} | ${AGENT_NAME} | FAILED | Required context file missing: $context_file | task:${TASK_ID} |" >> "$ERROR_LOG" || true
    exit 1
  fi
done

# 4. Ensure output and handoff directories exist
mkdir -p "$OUTPUT_DIR"
mkdir -p "$HANDOFF_DIR"
mkdir -p "$PROJECT_ROOT/agents/checkpoints"

# ============================================================
# Build context argument list
# Claude reads these files in the session before acting.
# Foundational documents are passed as context — not optional.
# ============================================================

CONTEXT_ARGS=()

# Always include the agent's prompt file first
CONTEXT_ARGS+=("--context" "$PROMPT_FILE")

# Foundational documents — always passed
for f in "$SESSION_BOOTSTRAP" "$PROJECT_INSTRUCTIONS" "$VISION_FILE"; do
  CONTEXT_ARGS+=("--context" "$f")
done

# Additional agent-specific context files (if any)
for f in "${ADDITIONAL_CONTEXT_FILES[@]+"${ADDITIONAL_CONTEXT_FILES[@]}"}"; do
  if [[ -n "$f" && -f "$f" ]]; then
    CONTEXT_ARGS+=("--context" "$f")
  fi
done

# ============================================================
# Invoke Claude CLI — atomic write pattern
# Write output to a temp file first, then rename to final path.
# This prevents partially-written files from being consumed by
# downstream agents if the run is interrupted.
# ============================================================

TEMP_OUTPUT=$(mktemp "${OUTPUT_DIR}/.${AGENT_NAME}_${TASK_ID}.tmp.XXXXXX")
FINAL_OUTPUT="${OUTPUT_DIR}/${AGENT_NAME}_${TASK_ID}_output.md"

echo "[${TIMESTAMP}] ${AGENT_NAME} [START]: task ${TASK_ID}"
echo "| ${TIMESTAMP} | ${AGENT_NAME} | STARTED | task:${TASK_ID} |" >> "$SESSION_LOG"

EXIT_CODE=0
claude \
  "${CONTEXT_ARGS[@]}" \
  --print \
  "You are ${AGENT_NAME}. Your prompt file, foundational documents, and task context have been loaded above.

Task ID: ${TASK_ID}
Checkpoint file: ${CHECKPOINT_FILE}

Before doing anything:
1. Confirm you have read the foundational documents loaded in this session.
2. Declare your blast radius — list every file and directory you intend to write to.
3. Verify all declared write targets are within your permitted directories.
4. Write a step-by-step plan to ${CHECKPOINT_FILE} before beginning.

Then execute your task. Write all outputs to disk. Update the checkpoint file as each step completes." \
  > "$TEMP_OUTPUT" 2>&1 || EXIT_CODE=$?

# ============================================================
# Handle exit status — rename temp file to final or .failed
# ============================================================

if [[ $EXIT_CODE -eq 0 ]]; then
  # Atomic rename: temp → final
  mv "$TEMP_OUTPUT" "$FINAL_OUTPUT"

  echo "[${TIMESTAMP}] ${AGENT_NAME} [COMPLETE]: task ${TASK_ID} → $FINAL_OUTPUT"
  echo "| ${TIMESTAMP} | ${AGENT_NAME} | COMPLETED | task:${TASK_ID} | output:${FINAL_OUTPUT} |" >> "$SESSION_LOG"

  # Write handoff envelope
  cat > "${HANDOFF_DIR}/${AGENT_NAME}_${TASK_ID}_handoff.json" << HANDOFF_EOF
{
  "task_id": "${TASK_ID}",
  "agent": "${AGENT_NAME}",
  "status": "COMPLETE",
  "output_location": "${FINAL_OUTPUT}",
  "inputs_consumed": ["${PROMPT_FILE}", "${SESSION_BOOTSTRAP}", "${PROJECT_INSTRUCTIONS}", "${VISION_FILE}"],
  "outputs_produced": ["${FINAL_OUTPUT}"],
  "flags": [],
  "audit_trail_ref": "${TIMESTAMP}"
}
HANDOFF_EOF

else
  # Preserve the failed output for diagnosis — rename with .failed extension
  FAILED_OUTPUT="${OUTPUT_DIR}/${AGENT_NAME}_${TASK_ID}_output.failed"
  mv "$TEMP_OUTPUT" "$FAILED_OUTPUT"

  echo "[${TIMESTAMP}] ${AGENT_NAME} [FAILED]: task ${TASK_ID} (exit code ${EXIT_CODE}) → $FAILED_OUTPUT" >&2
  echo "| ${TIMESTAMP} | ${AGENT_NAME} | FAILED | task:${TASK_ID} | exit:${EXIT_CODE} | output:${FAILED_OUTPUT} |" >> "$ERROR_LOG"

  # Write failed handoff envelope
  cat > "${HANDOFF_DIR}/${AGENT_NAME}_${TASK_ID}_handoff.json" << HANDOFF_EOF
{
  "task_id": "${TASK_ID}",
  "agent": "${AGENT_NAME}",
  "status": "FAILED",
  "output_location": "${FAILED_OUTPUT}",
  "inputs_consumed": ["${PROMPT_FILE}", "${SESSION_BOOTSTRAP}", "${PROJECT_INSTRUCTIONS}", "${VISION_FILE}"],
  "outputs_produced": [],
  "flags": ["exit_code_${EXIT_CODE}"],
  "audit_trail_ref": "${TIMESTAMP}"
}
HANDOFF_EOF

  exit $EXIT_CODE
fi
