#!/bin/bash
# {{PROJECT_NAME}} — Session entry script
# Generated by the wizard. Do not edit manually.
#
# Usage (run from project directory):
#   ./start-session.sh                    Standard start
#   ./start-session.sh --resume           Resume after planned pause
#   ./start-session.sh --resume --alert   Resume to respond to an alert

set -euo pipefail

# Model — resolved by the wizard from the tier mapping at setup time
MODEL="{{MODEL_HIGH}}"

# Resolve project directory from the script's own location
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$PROJECT_DIR"

# ── Parse flags ───────────────────────────────────────────────────────────────

RESUME=false
ALERT=false

for arg in "$@"; do
    case "$arg" in
        --resume) RESUME=true ;;
        --alert)  ALERT=true ;;
        *)
            echo ""
            echo "Unknown flag: $arg"
            echo "Usage: ./start-session.sh [--resume] [--alert]"
            echo ""
            exit 1
            ;;
    esac
done

# --alert without --resume is not a valid combination
if $ALERT && ! $RESUME; then
    echo ""
    echo "--alert must be used together with --resume."
    echo "Usage: ./start-session.sh --resume --alert"
    echo ""
    exit 1
fi

# ── Prerequisite checks ───────────────────────────────────────────────────────

# Claude Code CLI
if ! command -v claude &>/dev/null; then
    echo ""
    echo "Claude Code is not installed or cannot be found."
    echo "Run this to install it: npm install -g @anthropic-ai/claude-code"
    echo "Or see manual.md in this directory for the full setup guide."
    echo ""
    exit 1
fi

# Correct directory
if [ ! -f "session_bootstrap.md" ]; then
    echo ""
    echo "Cannot find session_bootstrap.md."
    echo "Make sure you are running this script from the project directory."
    echo "Expected location: $PROJECT_DIR"
    echo ""
    exit 1
fi

if [ ! -f "CLAUDE.md" ]; then
    echo ""
    echo "Cannot find CLAUDE.md."
    echo "Make sure you are running this script from the project directory."
    echo "Expected location: $PROJECT_DIR"
    echo ""
    exit 1
fi

# ── Banner ────────────────────────────────────────────────────────────────────

# Kickoff prompt — the FIRST message handed to the session so it orients itself and
# tells you what to do, instead of opening to a silent, blank prompt. (Claude Code does
# not take a turn until it receives a message; without this, running this script just
# launches Claude and waits, with no sign of what to do next.) The session follows the
# startup sequence in CLAUDE.md, reads its current state, and surfaces the next step in
# plain language before acting.
KICKOFF="Begin this session. Follow the session startup sequence in CLAUDE.md now: read session_bootstrap.md and the other startup files it lists, orient yourself to the current state, then tell me in plain language what to do next and wait for my go-ahead before doing it."

echo ""
if $ALERT; then
    echo "{{PROJECT_NAME}} — Alert response"
    echo "Loading system state. This will take a moment."
    echo "─────────────────────────────────────────────────────────"
    KICKOFF="This is an alert-response session. Read /logs/notification_log.md FIRST, identify what triggered the alert, and tell me in plain language what it is and the recommended response before doing anything else. Then follow the session startup sequence in CLAUDE.md and wait for my go-ahead."
elif $RESUME; then
    echo "{{PROJECT_NAME}} — Resuming session"
    echo "─────────────────────────────────────────────────────────"
else
    echo "{{PROJECT_NAME}} — Starting session"
    echo "─────────────────────────────────────────────────────────"
fi
echo ""

# ── Launch Claude Code ────────────────────────────────────────────────────────

# --effort high: this system's sessions reason at the high tier (the wizard resolved
# MODEL_HIGH above). Extended-thinking budgets are not a CLI flag; --effort is the
# supported knob for session reasoning effort (low|medium|high|xhigh|max).
# The trailing positional argument is the kickoff prompt (the session's first message),
# so the session orients + surfaces the next step instead of waiting at a blank prompt.
claude --model "$MODEL" --effort high "$KICKOFF"
