#!/bin/bash
# {{PROJECT_NAME}} — Session entry script
# Generated by the wizard. Do not edit manually.
#
# Usage (run from project directory):
#   ./start-session.sh                    Standard start
#   ./start-session.sh --resume           Resume after planned pause
#   ./start-session.sh --resume --alert   Resume to respond to an alert

set -euo pipefail

# Resolve project directory from the script's own location
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$PROJECT_DIR"

# ── Parse flags ───────────────────────────────────────────────────────────────

RESUME=false
ALERT=false

for arg in "$@"; do
    case "$arg" in
        --resume) RESUME=true ;;
        --alert)  ALERT=true ;;
        *)
            echo ""
            echo "Unknown flag: $arg"
            echo "Usage: ./start-session.sh [--resume] [--alert]"
            echo ""
            exit 1
            ;;
    esac
done

# --alert without --resume is not a valid combination
if $ALERT && ! $RESUME; then
    echo ""
    echo "--alert must be used together with --resume."
    echo "Usage: ./start-session.sh --resume --alert"
    echo ""
    exit 1
fi

# ── Prerequisite checks ───────────────────────────────────────────────────────

# Claude Code CLI
if ! command -v claude &>/dev/null; then
    echo ""
    echo "Claude Code is not installed or cannot be found."
    echo "Run this to install it: npm install -g @anthropic-ai/claude-code"
    echo "Or see manual.md in this directory for the full setup guide."
    echo ""
    exit 1
fi

# Correct directory
if [ ! -f "session_bootstrap.md" ]; then
    echo ""
    echo "Cannot find session_bootstrap.md."
    echo "Make sure you are running this script from the project directory."
    echo "Expected location: $PROJECT_DIR"
    echo ""
    exit 1
fi

if [ ! -f "CLAUDE.md" ]; then
    echo ""
    echo "Cannot find CLAUDE.md."
    echo "Make sure you are running this script from the project directory."
    echo "Expected location: $PROJECT_DIR"
    echo ""
    exit 1
fi

# ── Banner ────────────────────────────────────────────────────────────────────

echo ""
if $ALERT; then
    echo "{{PROJECT_NAME}} — Alert response"
    echo "Loading system state. This will take a moment."
    echo "─────────────────────────────────────────────────────────"
elif $RESUME; then
    echo "{{PROJECT_NAME}} — Resuming session"
    echo "─────────────────────────────────────────────────────────"
else
    echo "{{PROJECT_NAME}} — Starting session"
    echo "─────────────────────────────────────────────────────────"
fi
echo ""

# ── Launch Claude Code ────────────────────────────────────────────────────────

claude
